---
name: testing nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 3 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Nightly to show us in advance what will change in Python utilities in
  # the next version of Fedora
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # PYTHON CHECKS ON NEXT FEDORA PYTHON AND PYTHON TOOLS VERSION
          - dependencies: >
              pylint
              python3-dbus
              python3-psutil
            image: fedora:33
            task: PYTHONPATH=./src make -f Makefile lint
          - dependencies: black python3-isort
            image: fedora:33
            task: make -f Makefile fmt-travis
    runs-on: ubuntu-18.04
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          python-unversioned-command
          ${{ matrix.dependencies }}
      - name: Run test
        run: ${{ matrix.task }}
